/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "train.h"

bool_t
xdr_seat (XDR *xdrs, seat *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->row))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->col))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_available (XDR *xdrs, available objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 40,
		sizeof (seat), (xdrproc_t) xdr_seat))
		 return FALSE;
	return TRUE;
}
