/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "train.h"

int *
reserve_seat_1_svc(seat *argp, struct svc_req *rqstp)
{
	static int  result;
	seat s = *argp;
	printf("ASIENTO: (%d, %d)\n", s.row, s.col);
	result = 1;
	return &result;
}
