/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "train.h"


void
train_1(char *host, char *row, char *col)
{
	CLIENT *clnt;
	int  *result_1;
	seat  reserve_seat_1_arg;
	reserve_seat_1_arg.row = atoi(row);
	reserve_seat_1_arg.col = atoi(col);

#ifndef	DEBUG
	clnt = clnt_create (host, TRAIN, TRAIN_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = reserve_seat_1(&reserve_seat_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("LO LOGRE %d\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	train_1 (host, argv[2], argv[3]);
exit (0);
}
