/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "train.h"

bool_t
xdr_seat (XDR *xdrs, seat *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->row))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->col))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_available (XDR *xdrs, available *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->list.list_val, (u_int *) &objp->list.list_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
