/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRAIN_H_RPCGEN
#define _TRAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_ROW 10
#define MAX_COL 4

struct seat {
	int row;
	int col;
};
typedef struct seat seat;

struct available {
	struct {
		u_int list_len;
		int *list_val;
	} list;
};
typedef struct available available;

#define TRAIN 0x31111111
#define TRAIN_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define is_wagon_full 1
extern  int * is_wagon_full_1(void *, CLIENT *);
extern  int * is_wagon_full_1_svc(void *, struct svc_req *);
#define is_seat_taken 2
extern  available * is_seat_taken_1(seat *, CLIENT *);
extern  available * is_seat_taken_1_svc(seat *, struct svc_req *);
#define reserve_seat 3
extern  int * reserve_seat_1(seat *, CLIENT *);
extern  int * reserve_seat_1_svc(seat *, struct svc_req *);
extern int train_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define is_wagon_full 1
extern  int * is_wagon_full_1();
extern  int * is_wagon_full_1_svc();
#define is_seat_taken 2
extern  available * is_seat_taken_1();
extern  available * is_seat_taken_1_svc();
#define reserve_seat 3
extern  int * reserve_seat_1();
extern  int * reserve_seat_1_svc();
extern int train_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_seat (XDR *, seat*);
extern  bool_t xdr_available (XDR *, available*);

#else /* K&R C */
extern bool_t xdr_seat ();
extern bool_t xdr_available ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRAIN_H_RPCGEN */
